package Main;

import entity.NPC_Merchant;
import entity.NPC_OldMan;
import monster.MON_GreenSlime;
import monster.MON_Orc;
import object.*;
import tile_interactive.IT_DryTree;

public class AssetSetter {
    GamePanel gp;

    public AssetSetter(GamePanel gp){
        this.gp = gp;
    }
    public void setObject(){
        int mapNum = 0;
        int i = 0;
        gp.obj[mapNum][i] = new OBJ_Key(gp);
        gp.obj[mapNum][i].worldX = 133 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 142 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Key(gp);
        gp.obj[mapNum][i].worldX = 188 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 105 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 151 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 125 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 99 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 125 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 125 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 151 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 125 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 99 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 159 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 213 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Door(gp);
        gp.obj[mapNum][i].worldX = 160 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 213 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Chest(gp);
        gp.obj[mapNum][i].setLoot(new OBJ_Key(gp));
        gp.obj[mapNum][i].worldX = 162 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 184 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Axe(gp);
        gp.obj[mapNum][i].worldX = 141 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 132 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Potion_Red(gp);
        gp.obj[mapNum][i].worldX = 143 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 117 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Potion_Red(gp);
        gp.obj[mapNum][i].worldX = 133 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 107 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Heart(gp);
        gp.obj[mapNum][i].worldX = 117 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 107 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_ManaCrystal(gp);
        gp.obj[mapNum][i].worldX = 106 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 117 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Lantern(gp);
        gp.obj[mapNum][i].worldX = 107 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 132 * gp.tileSize;
        i++;
        gp.obj[mapNum][i] = new OBJ_Tent(gp);
        gp.obj[mapNum][i].worldX = 118 * gp.tileSize;
        gp.obj[mapNum][i].worldY = 142 * gp.tileSize;
        i++;
    }
    public void setNPC(){
        int mapNum = 0;
        int i = 0;
        gp.npc[mapNum][i] = new NPC_OldMan(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize*129;
        gp.npc[mapNum][i].worldY = gp.tileSize*134;
        i++;
        mapNum = 1;
        i = 0;
        gp.npc[mapNum][i] = new NPC_Merchant(gp);
        gp.npc[mapNum][i].worldX = gp.tileSize*12;
        gp.npc[mapNum][i].worldY = gp.tileSize*7;
        i++;
    }
    public void setMonster(){
        int mapNum = 0;
        int i = 0;
        gp.monster[mapNum][i] = new MON_GreenSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 177;
        gp.monster[mapNum][i].worldY = gp.tileSize * 100;
        i++;
        gp.monster[mapNum][i] = new MON_GreenSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 182;
        gp.monster[mapNum][i].worldY = gp.tileSize * 96;
        i++;
        gp.monster[mapNum][i] = new MON_GreenSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 175;
        gp.monster[mapNum][i].worldY = gp.tileSize * 103;
        i++;
        gp.monster[mapNum][i] = new MON_GreenSlime(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 185;
        gp.monster[mapNum][i].worldY = gp.tileSize * 99;
        i++;
        gp.monster[mapNum][i] = new MON_Orc(gp);
        gp.monster[mapNum][i].worldX = gp.tileSize * 159;
        gp.monster[mapNum][i].worldY = gp.tileSize * 216;
        i++;
    }
    public void setInteractiveTile(){
        int mapNum = 0;
        int i = 0;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,153,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,154,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,155,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,156,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,157,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,158,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,159,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,160,108);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,160,107);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,106);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,105);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,104);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,103);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,102);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,101);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,161,100);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,162,100);
        i++;
        gp.iTile[mapNum][i] = new IT_DryTree(gp,162,99);
        i++;
    }
}
