package Main;

import java.io.*;

public class config {
    Panel_de_Juego gp;
    public config(Panel_de_Juego gp){
        this.gp = gp;
    }
    public void guardarconfig(){
        try{
            BufferedWriter bw = new BufferedWriter(new FileWriter("config"));
            // pantalla completa
            if(gp.pantallacompletaon == true){
                bw.write("On");
            }if(gp.pantallacompletaon == false){
                bw.write("Off");
            }
            bw.newLine();
            // volumen musica
            bw.write(String.valueOf(gp.musica.escalavolumen));
            bw.newLine();
            // se volumen
            bw.write(String.valueOf(gp.se.escalavolumen));
            bw.newLine();
            bw.close();
        } catch (IOException e){
            // todo autogenerated
            e.printStackTrace();
        }
    }
    public void cargarconfig(){
        try{
            BufferedReader br = new BufferedReader(new FileReader("config"));
            String s = br.readLine();
            // pantalla completa
            if(s.equals("On")){
                gp.pantallacompletaon = true;
            }
            if(s.equals("Off")){
                gp.pantallacompletaon = false;
            }
            // volumen msica
            s = br.readLine();
            gp.musica.escalavolumen = Integer.parseInt(s);
            // se volumen
            s = br.readLine();
            gp.se.escalavolumen = Integer.parseInt(s);
            br.close();
        } catch (Exception e){
            e.printStackTrace();
        }

    }
}
